# Site settings
title: SKKU OSS Team 126B
email: miru2533@skku.edu
description: SKKU OSS
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

#baseurl: "/126B/" # the subpath of your site, e.g. /blog/
#url: "https://github.com/17-1-SKKU-OSS/126B" # the base hostname & protocol for your site
site: https://17-1-skku-oss.github.io/126B/
# twitter_username: jekyllrb
github_username: 17-1-SKKU-OSS/126B
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/17-1-SKKU-OSS/126B/tree/gh-pages
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/17-1-SKKU-OSS/126B/tree/gh-pages
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
#disqus_shortname: lixizhi
#disqus_url: "http://lixizhi.github.io"
#########################################

# Build settings
markdown: kramdown


# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
